# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

Firstly, let's select TensorFlow version 2.x in colab

In [32]:
%tensorflow_version 2.x
import tensorflow as tf
tf.__version__

'2.1.0'

In [0]:
# Initialize the random number generator
import random
random.seed(0)

# Ignore the warnings
import warnings
warnings.filterwarnings("ignore")

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X= iris.data
Y= iris.target

In [12]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [13]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state: 1
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y ,test_size= 0.25, random_state=1, stratify=Y)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:

Y_train = tf.keras.utils.to_categorical(Y_train, 3)
Y_test = tf.keras.utils.to_categorical(Y_test, 3)

In [16]:
Y_train

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0

In [17]:
Y_train.shape ## There are 112 matrices with 3*3 dimensions

(112, 3)

In [18]:
Y_test.shape ## There are 38 matrices with 3*3 dimensions

(38, 3)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [19]:
import numpy as np
import pandas as pd
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline



# Using Tensorflow Keras instead of the original Keras

from tensorflow.keras.datasets import mnist
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

from keras.callbacks import EarlyStopping
from keras.layers import BatchNormalization


#Initialize sequential model
model= Sequential()

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

Using TensorFlow backend.


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
#Add Dense Layer  applying softmax

#Add an input layer 
model.add(Dense(3, activation='softmax', input_shape=(4,)))


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
#Compile the model
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [23]:
model.summary


<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f0f3129ff60>>

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [26]:
epochs = 100
batch_size = 150


history = model.fit(X_train, Y_train, batch_size=batch_size, epochs=epochs, validation_split=.1, verbose=True)
loss,accuracy  = model.evaluate(X_test, Y_test, verbose=False)

Train on 100 samples, validate on 12 samples
Epoch 1/100
100/100 [==============================] - 0s 120us/sample - loss: 0.5554 - accuracy: 0.7800 - val_loss: 0.7007 - val_accuracy: 0.6667
Epoch 2/100
100/100 [==============================] - 0s 102us/sample - loss: 0.5535 - accuracy: 0.7800 - val_loss: 0.6974 - val_accuracy: 0.6667
Epoch 3/100
100/100 [==============================] - 0s 114us/sample - loss: 0.5517 - accuracy: 0.7800 - val_loss: 0.6942 - val_accuracy: 0.6667
Epoch 4/100
100/100 [==============================] - 0s 106us/sample - loss: 0.5499 - accuracy: 0.7800 - val_loss: 0.6910 - val_accuracy: 0.6667
Epoch 5/100
100/100 [==============================] - 0s 105us/sample - loss: 0.5482 - accuracy: 0.7800 - val_loss: 0.6878 - val_accuracy: 0.6667
Epoch 6/100
100/100 [==============================] - 0s 105us/sample - loss: 0.5465 - accuracy: 0.7800 - val_loss: 0.6846 - val_accuracy: 0.6667
Epoch 7/100
100/100 [==============================] - 0s 106us/sample - 

In [27]:
loss, acc = model.evaluate(X_test, Y_test, verbose=0)
print('Accuracy: %.3f'  % acc)
print('Loss: %.3f' % loss)

Accuracy: 0.737
Loss: 0.606


## Question 10

### Make predictions
- Predict labels on one row

In [28]:
model.predict(X_test[0:1])

array([[0.04243349, 0.2592638 , 0.69830275]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [29]:
Y_test[0:1]

array([[0., 0., 1.]], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

In this assignment, we will work on the stock prices dataset named "prices.csv". Task is to create a Neural Network to classify closing price for a stock based on some parameters.

Firstly, let's select TensorFlow version 2.x in colab

In [30]:
%tensorflow_version 2.x
import tensorflow
tensorflow.__version__

'2.1.0'

In [0]:
# Initialize the random number generator
import random
random.seed(0)

# Ignore the warnings
import warnings
warnings.filterwarnings("ignore")

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [35]:
# run this cell to upload file using GUI if you are using google colab

from google.colab import files
files.upload()

{}

In [36]:
# run this cell to to mount the google drive if you are using google colab

from google.colab import drive
drive.mount('/content/drive')

df= pd.read_csv('/content/prices.csv')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

In [0]:
from google.colab import drive
drive.mount('/content/drive')

## Question 2

### Drop null
- Drop null values if any

In [37]:
df.isnull().sum()

date      0
symbol    1
open      1
close     1
low       1
high      1
volume    1
dtype: int64

In [0]:
df.dropna(axis=0,inplace=True)

### Drop columnns
- Now, we don't need "date", "volume" and "symbol" column
- drop "date", "volume" and "symbol" column from the data


In [0]:
df_modi = df.drop(['date','volume','symbol'],axis=1)

## Question 3

### Print the dataframe
- print the modified dataframe

In [41]:
df_modi

open       close         low        high
0      123.430000  125.839996  122.309998  126.250000
1      125.239998  119.980003  119.940002  125.540001
2      116.379997  114.949997  114.930000  119.739998
3      115.480003  116.620003  113.500000  117.440002
4      117.010002  114.970001  114.089996  117.330002
...           ...         ...         ...         ...
88884   78.019997   77.269997   76.510002   78.260002
88885   58.080002   58.099998   57.750000   58.470001
88886   18.139999   17.690001   17.650000   18.200001
88887   16.320000   16.389999   15.970000   16.389999
88888   44.110001   43.610001   43.529999   44.340000

[88889 rows x 4 columns]

### Get features and label from the dataset in separate variable
- Let's separate labels and features now. We are going to predict the value for "close" column so that will be our label. Our features will be "open", "low", "high"
- Take "open" "low", "high" columns as features
- Take "close" column as label

In [0]:
X= df_mod.drop(['close'],axis=1)
y = df_mod['close']

## Question 4

### Create train and test sets
- Split the data into training and testing

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1,test_size=0.3)

## Question 5

### Scaling
- Scale the data (features only)
- Use StandarScaler

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train =sc.fit_transform(X_train)
X_test =sc.fit_transform(X_test)
X_train

array([[-0.13105339, -0.1356901 , -0.13434787],
       [ 0.24158521,  0.25423878,  0.23913162],
       [-0.48277869, -0.48177067, -0.48859961],
       ...,
       [-0.70838982, -0.71641249, -0.70971955],
       [-0.30659919, -0.30038856, -0.30447229],
       [-0.38877402, -0.38894064, -0.39434148]])

## Question 6

### Convert data to NumPy array
- Convert features and labels to numpy array

In [0]:
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

### Reshape features
- Reshape the features to make it suitable for input in the model 

In [46]:
X_train.shape

(62222, 3)

In [0]:
X_train = X_train.reshape(X_train.shape[0],X_train.shape[1],1)
X_test= X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Question 7

### Define Model
- Initialize a Sequential model
- Add a Flatten layer
- Add a Dense layer with one neuron as output
  - add 'linear' as activation function


In [0]:

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense , Flatten
from keras.layers.advanced_activations import ReLU

# define the model architecture

# Initialize the constructor
model_1 = Sequential()
model_1.add(Flatten())
model_1.add(Dense(1,activation = 'linear'))

## Question 8

### Compile the model
- Compile the model
- Use "sgd" optimizer
- for calculating loss, use mean squared error

In [0]:
model_1.compile(loss='mean_squared_error',
              optimizer='sgd',)

## Question 9

### Fit the model
- epochs: 50
- batch size: 128
- specify validation data

In [52]:
epochs = 50
batch_size = 128

epochs = 50
batchsize = 128
validation = (X_test,y_test)
history = model_1.fit(X_train, y_train, epochs=epochs,batch_size = batchsize,validation_data=validation, verbose=True)

Train on 62222 samples, validate on 26667 samples
Epoch 1/50
62222/62222 [==============================] - 1s 13us/sample - loss: 0.4879 - val_loss: 6.1583
Epoch 2/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4874 - val_loss: 6.2630
Epoch 3/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4846 - val_loss: 6.6236
Epoch 4/50
62222/62222 [==============================] - 1s 13us/sample - loss: 0.4857 - val_loss: 6.1931
Epoch 5/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4853 - val_loss: 6.8851
Epoch 6/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4855 - val_loss: 6.2072
Epoch 7/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4827 - val_loss: 6.5185
Epoch 8/50
62222/62222 [==============================] - 1s 14us/sample - loss: 0.4823 - val_loss: 6.5750
Epoch 9/50
62222/62222 [==============================] - 1s 13us/sample - loss: 0.4816 - val_

## Question 10

### Evaluate the model
- Evaluate the model on test data

In [54]:
loss= model_1.evaluate(X_test, y_test, verbose=0)
print('Test Loss: %.3f' %loss)

Test Loss: 6.374


### Manual predictions
- Test the predictions on manual inputs
- We have scaled out training data, so we need to transform our custom inputs using the object of the scaler
- Example of manual input: [123.430000,	122.30999, 116.250000]

In [56]:
sample1 = [123.430000, 122.30999, 116.250000]
sample1 = sc.transform([sample1])
sample1

array([[1.70344445, 1.71268669, 1.51382269]])

In [0]:
manual_predict=model_1.predict([sample1])

In [58]:
manual_predict

array([[124.585556]], dtype=float32)