In [59]:
# Import important library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

### Q1 Read the input file and check the data dimension

In [60]:
#Read input file and understand the data
# "default" is my dependent variable

In [61]:
df=pd.read_csv("german_credit.csv")
target=df['default']              #default is the target variable
df=df.drop('default',axis=1)
df.shape

(1000, 20)

In [62]:
df.head()

account_check_status  duration_in_month  \
0               < 0 DM                  6   
1    0 <= ... < 200 DM                 48   
2  no checking account                 12   
3               < 0 DM                 42   
4               < 0 DM                 24   

                                      credit_history  \
0  critical account/ other credits existing (not ...   
1           existing credits paid back duly till now   
2  critical account/ other credits existing (not ...   
3           existing credits paid back duly till now   
4                    delay in paying off in the past   

                        purpose  credit_amount                      savings  \
0           domestic appliances           1169  unknown/ no savings account   
1           domestic appliances           5951                 ... < 100 DM   
2  (vacation - does not exist?)           2096                 ... < 100 DM   
3              radio/television           7882                 ... < 100 DM   
4                     car (new)           4870                 ... < 100 DM   

    present_emp_since  installment_as_income_perc  \
0       .. >= 7 years                           4   
1  1 <= ... < 4 years                           2   
2  4 <= ... < 7 years                           2   
3  4 <= ... < 7 years                           2   
4  1 <= ... < 4 years                           3   

                   personal_status_sex other_debtors  present_res_since  \
0                        male : single          none                  4   
1  female : divorced/separated/married          none                  2   
2                        male : single          none                  3   
3                        male : single     guarantor                  4   
4                        male : single          none                  4   

                                            property  age  \
0                                        real estate   67   
1                                        real estate   22   
2                                        real estate   49   
3  if not A121 : building society savings agreeme...   45   
4                              unknown / no property   53   

  other_installment_plans   housing  credits_this_bank  \
0                    none       own                  2   
1                    none       own                  1   
2                    none       own                  1   
3                    none  for free                  1   
4                    none  for free                  2   

                           job  people_under_maintenance  \
0  skilled employee / official                         1   
1  skilled employee / official                         1   
2         unskilled - resident                         2   
3  skilled employee / official                         2   
4  skilled employee / official                         2   

                                   telephone foreign_worker  
0  yes, registered under the customers name             yes  
1                                       none            yes  
2                                       none            yes  
3                                       none            yes  
4                                       none            yes

In [63]:
# Lets build a Ensemble model but need to modify the dataset first

### Q2.Prepare the model data by converting non-numeric to dummy ( 1 Marks)
##### Hint: Use get_dummies

In [64]:
#no missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
account_check_status          1000 non-null object
duration_in_month             1000 non-null int64
credit_history                1000 non-null object
purpose                       1000 non-null object
credit_amount                 1000 non-null int64
savings                       1000 non-null object
present_emp_since             1000 non-null object
installment_as_income_perc    1000 non-null int64
personal_status_sex           1000 non-null object
other_debtors                 1000 non-null object
present_res_since             1000 non-null int64
property                      1000 non-null object
age                           1000 non-null int64
other_installment_plans       1000 non-null object
housing                       1000 non-null object
credits_this_bank             1000 non-null int64
job                           1000 non-null object
people_under_maintenance      100

In [65]:
non_numeric_columns=df.columns[df.dtypes==object]
non_numeric_columns

Index(['account_check_status', 'credit_history', 'purpose', 'savings',
       'present_emp_since', 'personal_status_sex', 'other_debtors', 'property',
       'other_installment_plans', 'housing', 'job', 'telephone',
       'foreign_worker'],
      dtype='object')

In [66]:
df=pd.get_dummies(df,columns=non_numeric_columns)
df.head()

duration_in_month  credit_amount  installment_as_income_perc  \
0                  6           1169                           4   
1                 48           5951                           2   
2                 12           2096                           2   
3                 42           7882                           2   
4                 24           4870                           3   

   present_res_since  age  credits_this_bank  people_under_maintenance  \
0                  4   67                  2                         1   
1                  2   22                  1                         1   
2                  3   49                  1                         2   
3                  4   45                  1                         2   
4                  4   53                  2                         2   

   account_check_status_0 <= ... < 200 DM  account_check_status_< 0 DM  \
0                                       0                            1   
1                                       1                            0   
2                                       0                            0   
3                                       0                            1   
4                                       0                            1   

   account_check_status_>= 200 DM / salary assignments for at least 1 year  \
0                                                  0                         
1                                                  0                         
2                                                  0                         
3                                                  0                         
4                                                  0                         

          ...          housing_own  housing_rent  \
0         ...                    1             0   
1         ...                    1             0   
2         ...                    1             0   
3         ...                    0             0   
4         ...                    0             0   

   job_management/ self-employed/ highly qualified employee/ officer  \
0                                                  0                   
1                                                  0                   
2                                                  0                   
3                                                  0                   
4                                                  0                   

   job_skilled employee / official  job_unemployed/ unskilled - non-resident  \
0                                1                                         0   
1                                1                                         0   
2                                0                                         0   
3                                1                                         0   
4                                1                                         0   

   job_unskilled - resident  telephone_none  \
0                         0               0   
1                         0               1   
2                         1               1   
3                         0               1   
4                         0               1   

   telephone_yes, registered under the customers name   foreign_worker_no  \
0                                                  1                    0   
1                                                  0                    0   
2                                                  0                    0   
3                                                  0                    0   
4                                                  0                    0   

   foreign_worker_yes  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  

[5 rows x 61 columns]

### Check for highly correlated variables but don't required any treatment for this use case

In [67]:
corr=df.corr() 
corr

duration_in_month  \
duration_in_month                                            1.000000   
credit_amount                                                0.624984   
installment_as_income_perc                                   0.074749   
present_res_since                                            0.034067   
age                                                         -0.036136   
credits_this_bank                                           -0.011284   
people_under_maintenance                                    -0.023834   
account_check_status_0 <= ... < 200 DM                       0.089452   
account_check_status_< 0 DM                                  0.022244   
account_check_status_>= 200 DM / salary assignm...          -0.076455   
account_check_status_no checking account                    -0.063467   
credit_history_all credits at this bank paid ba...           0.033728   
credit_history_critical account/ other credits ...          -0.075575   
credit_history_delay in paying off in the past               0.136927   
credit_history_existing credits paid back duly ...          -0.069751   
credit_history_no credits taken/ all credits pa...           0.118077   
purpose_(vacation - does not exist?)                         0.003750   
purpose_business                                             0.164113   
purpose_car (new)                                           -0.109999   
purpose_car (used)                                           0.144939   
purpose_domestic appliances                                 -0.044319   
purpose_education                                           -0.022549   
purpose_furniture/equipment                                  0.104516   
purpose_radio/television                                    -0.062804   
purpose_repairs                                             -0.037212   
purpose_retraining                                          -0.072151   
savings_.. >= 1000 DM                                       -0.048261   
savings_... < 100 DM                                        -0.047228   
savings_100 <= ... < 500 DM                                  0.051587   
savings_500 <= ... < 1000 DM                                -0.040257   
...                                                               ...   
present_emp_since_.. >= 7 years                              0.017471   
present_emp_since_... < 1 year                              -0.056792   
present_emp_since_1 <= ... < 4 years                        -0.031920   
present_emp_since_4 <= ... < 7 years                         0.079635   
present_emp_since_unemployed                                -0.005156   
personal_status_sex_female : divorced/separated...          -0.081432   
personal_status_sex_male : divorced/separated                0.006415   
personal_status_sex_male : married/widowed                  -0.084418   
personal_status_sex_male : single                            0.121889   
other_debtors_co-applicant                                   0.029698   
other_debtors_guarantor                                     -0.039594   
other_debtors_none                                           0.009993   
property_if not A121 : building society savings...          -0.056706   
property_if not A121/A122 : car or other, not i...           0.119486   
property_real estate                                        -0.242586   
property_unknown / no property                               0.212838   
other_installment_plans_bank                                 0.035851   
other_installment_plans_none                                -0.067602   
other_installment_plans_stores                               0.065688   
housing_for free                                             0.189117   
housing_own                                                 -0.075169   
housing_rent                                                -0.064417   
job_management/ self-employed/ highly qualified...           0.147515   
job_skilled employee / official      

In [68]:
corr.style.background_gradient(cmap='coolwarm')

In [69]:
# credit_amount and duration_in_month are the highly positively correlated variables with p =0.625
# property_unknown / no property and housing_for free have a high positive correlation of p=0.77
# other_installment_plans_bank and	other_installment_plans_none are having high negative correlation of p=-0.81

### Q3 Split Train/Test data 70:30 ratio( 1 Marks)
##### Hint:from sklearn.model_selection import train_test_split

In [70]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df,target,test_size=.3,random_state=0)
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(700, 61) (300, 61) (700,) (300,)


### Q4 Build Random Forest Model( 2 Marks)
#### Hint:from sklearn.ensemble import RandomForestClassifier using n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999

In [71]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_jobs=2,n_estimators=500,criterion="entropy",random_state=9999)
rfc.fit(X_train,y_train)
predictions=rfc.predict(X_test)

### Q5 Calculate Confusion Matrix and Accuracy score (1 Marks)
##### Hint: Use confusion_matrix and accuracy_score

In [72]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy = accuracy_score(y_test,predictions)
cm = confusion_matrix(y_test,predictions) 
print('Accuracy score: ',accuracy,'\nConfusion Matrix: \n',cm)

Accuracy score:  0.76 
Confusion Matrix: 
 [[190  24]
 [ 48  38]]


### Q6 Show the list of the features importance( 1 Marks)

In [73]:
rfc.feature_importances_

array([0.07715517, 0.10084407, 0.03380165, 0.03418452, 0.07570705,
       0.01928814, 0.01333799, 0.0161585 , 0.0343193 , 0.00922311,
       0.04811108, 0.01223125, 0.01957902, 0.01052372, 0.01357139,
       0.0131111 , 0.00683678, 0.00961554, 0.01591767, 0.01298015,
       0.0132362 , 0.00473384, 0.0018147 , 0.01269195, 0.00306797,
       0.00136354, 0.0057712 , 0.01625968, 0.00883586, 0.00736447,
       0.01488955, 0.01408868, 0.01631156, 0.01468107, 0.01270602,
       0.00607175, 0.01405851, 0.0066096 , 0.00966621, 0.01483113,
       0.00663389, 0.00935524, 0.00891751, 0.01355306, 0.01422617,
       0.01894243, 0.0100308 , 0.01267457, 0.01465725, 0.0062234 ,
       0.00660387, 0.01375897, 0.01221152, 0.01028214, 0.01586767,
       0.00267613, 0.01193502, 0.01515098, 0.01390453, 0.00332942,
       0.00351476])

### Q7 K-fold cross-validation( 2 Marks)
##### k-fold cross validation( without stratification)
##### Usually k is set as 10-20 in practical settings, depends on data set size

In [74]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [75]:
# Use below values
num_folds = 10
seed = 77

In [76]:
#Validate the Random Forest model build above using k fold
kfold=KFold(num_folds,random_state=seed)
accuracy=[]
for train,test in kfold.split(df,target):
        Xtrain,Xtest=df.iloc[train,:],df.iloc[test,:]
        Ytrain,Ytest=target.iloc[train],target.iloc[test]
        rfc.fit(Xtrain,Ytrain)
        Y_predict=rfc.predict(Xtest)
        accuracy.append(accuracy_score(Ytest,Y_predict))

In [77]:
#accuracies for Kfold cross validation
accuracy

[0.86, 0.71, 0.76, 0.79, 0.8, 0.67, 0.74, 0.8, 0.76, 0.76]

In [78]:
#Calculate Mean score

In [79]:
mean_accuracy_score=np.mean(accuracy)
print('Mean score:',mean_accuracy_score)

Mean score: 0.765


In [80]:
# Calculate score standard deviation using std()

In [81]:
print('score standard deviation:',np.std(accuracy))

score standard deviation: 0.049849774322458074


# Q8 Build Ada boosting model, check the accuracy, and print confusion matrix ( 1 Marks)

In [82]:
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=50)
abc.fit(X_train,y_train)
predictions=abc.predict(X_test)
print("Accuracy of Ada Boosting model : ",accuracy_score(y_test,predictions))
print("Confusion Matrix : \n",confusion_matrix(y_test,predictions))

Accuracy of Ada Boosting model :  0.7633333333333333
Confusion Matrix : 
 [[181  33]
 [ 38  48]]


# Q9. Build Gradient boosting model, check the accuracy, and print confusion matrix ( 1 Marks)
percentage of correct predictions and Calculate sensitivity (or True Positive Rate or Recall) and Precision.
( 1 Marks)

In [83]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=50)
gbc.fit(X_train,y_train)
predictions=gbc.predict(X_test)
print("Accuracy of Gradient boosting model : ",accuracy_score(y_test,predictions))
print("Confusion Matrix : \n",confusion_matrix(y_test,predictions))

Accuracy of Gradient boosting model :  0.77
Confusion Matrix : 
 [[195  19]
 [ 50  36]]


In [84]:
print('Percentage of correct predictions( i.e TP + FP / total ) : ',((194+36)/(194+20+50+36))*100,'%')
print('Sensitivity- Recall ( TP/(TP + FN)) : ',(36)/(50+36))
print('Precision ( TP/(TP + FP)) : ',(36)/(20+36))

Percentage of correct predictions( i.e TP + FP / total ) :  76.66666666666667 %
Sensitivity- Recall ( TP/(TP + FN)) :  0.4186046511627907
Precision ( TP/(TP + FP)) :  0.6428571428571429


### Bootstrapping ( Bonus)
##### Given a dataset of size n, a bootstrap sample is created by sampling n instances uniformly from the data (with/without replacement)
##### Create a model with each bootstrap sample and validate it with the test set
##### Final result is calculated by averaging the accuracy of models

In [85]:
# Number of iterations for bootstrapping
bootstrap_iteration = 10
accuracy = []

In [88]:
from sklearn.utils import resample
from sklearn.metrics import accuracy_score

for i in range(bootstrap_iteration):
    X_, y_ = resample(X_train, y_train)
    rfc.fit(X_, y_)
    y_pred = rfc.predict(X_test)
    
    acc = accuracy_score(y_pred, y_test)
    accuracy.append(acc)

In [89]:
accuracy = np.array(accuracy)
print('Accuracy Score')
print('Avearge: ', accuracy.mean())
print('Standard deviation: ', accuracy.std())

Accuracy Score
Avearge:  0.7636666666666667
Standard deviation:  0.012600705447623877
